services:
  patent-searcher:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: patent-searcher-backend
    image: patent-search:latest
    restart: always
    hostname: patent-searcher-backend
    working_dir: /app
    command: 
      - pm2-runtime
      - start
      - ecosystem.config.cjs
      - --env
      - ${env}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./database:/app/database
      - ./logs:/app/logs
    ports:
      - 8081:8030